cyt:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 12345678
  aliyun:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tN3jGgN8GgBSLD2KYP2
    access-key-secret: DdfmrMo1cAJVtmIHQizmFUj3J8yC7s
    bucket-name: cyt-sky-take-out
