server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${cyt.datasource.driver-class-name}
      url: jdbc:mysql://${cyt.datasource.host}:${cyt.datasource.port}/${cyt.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${cyt.datasource.username}
      password: ${cyt.datasource.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cyt.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      cyt:
        mapper: debug
        service: info
        controller: info

cyt:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

  aliyun:
    endpoint: ${cyt.aliyun.endpoint}
    access-key-id: ${cyt.aliyun.access-key-id}}
    access-key-secret: ${cyt.aliyun.access-key-secret}
    bucket-name: ${cyt.aliyun.bucket-name}